//! PRD index generator.
//!
//! Scans the `.mr/prds/` directory for PRD files and generates an index
//! in `.mr/PRDS.md` with a table listing all PRDs.

use std::collections::HashMap;
use std::path::Path;

use anyhow::{Context, Result};

use super::{Prd, PrdStatus, parse_prd_file};

/// Summary of a PRD for the index.
#[derive(Debug, Clone)]
pub struct PrdSummary {
    /// PRD ID (e.g., "PRD-0001").
    pub id: String,

    /// PRD title.
    pub title: String,

    /// PRD status.
    pub status: PrdStatus,

    /// Number of completed tasks.
    pub completed_tasks: usize,

    /// Total number of tasks.
    pub total_tasks: usize,

    /// Relative path to the PRD file from the index file's directory.
    pub relative_path: String,

    /// Absolute path to the PRD file.
    #[allow(dead_code)]
    pub path: std::path::PathBuf,
}

impl PrdSummary {
    /// Creates a new PrdSummary from a Prd and its file path.
    pub fn from_prd(prd: &Prd, relative_path: String, absolute_path: std::path::PathBuf) -> Self {
        let tasks = prd.tasks().unwrap_or_default();
        let completed_tasks = prd.completed_tasks().len();
        let total_tasks = tasks.len();

        Self {
            id: prd.id().to_string(),
            title: prd.title().to_string(),
            status: prd.status(),
            completed_tasks,
            total_tasks,
            relative_path,
            path: absolute_path,
        }
    }

    /// Returns a progress string like "3/10".
    pub fn progress(&self) -> String {
        format!("{}/{}", self.completed_tasks, self.total_tasks)
    }
}

/// Scans a directory for PRD files and returns parsed PRDs.
///
/// # Arguments
///
/// * `prds_dir` - Path to the directory containing PRD files (e.g., `.mr/prds/`)
///
/// # Returns
///
/// A vector of (filename, Prd, absolute_path) tuples for successfully parsed PRDs.
/// Files that fail to parse are logged and skipped.
pub fn scan_prds(prds_dir: impl AsRef<Path>) -> Result<Vec<(String, Prd, std::path::PathBuf)>> {
    let prds_dir = prds_dir.as_ref();

    if !prds_dir.exists() {
        return Ok(Vec::new());
    }

    let mut prds = Vec::new();

    let entries = std::fs::read_dir(prds_dir)
        .with_context(|| format!("Failed to read PRDs directory: {}", prds_dir.display()))?;

    for entry in entries {
        let entry = entry?;
        let path = entry.path();

        // Only process .md files.
        if path.extension().is_some_and(|ext| ext == "md") {
            let filename = entry.file_name().to_string_lossy().to_string();

            match parse_prd_file(&path) {
                Ok(prd) => {
                    prds.push((filename, prd, path));
                }
                Err(e) => {
                    tracing::warn!(
                        path = %path.display(),
                        error = %e,
                        "Failed to parse PRD file, skipping"
                    );
                }
            }
        }
    }

    // Sort by ID for deterministic output.
    prds.sort_by(|a, b| a.1.id().cmp(b.1.id()));

    Ok(prds)
}

/// Generates the PRDS.md index content.
///
/// # Arguments
///
/// * `prds` - Vector of (filename, Prd, absolute_path) tuples
///
/// # Returns
///
/// The generated Markdown content for the index file.
pub fn generate_index(prds: &[(String, Prd, std::path::PathBuf)]) -> String {
    let mut output = String::new();

    // Header.
    output.push_str("# Micro Ralph — PRD Index\n\n");
    output.push_str("This file is auto-generated by `mr`. Do not edit manually.\n\n");

    // Group PRDs by status.
    let mut by_status: HashMap<PrdStatus, Vec<PrdSummary>> = HashMap::new();

    for (filename, prd, abs_path) in prds {
        let relative_path = format!("prds/{}", filename);
        let summary = PrdSummary::from_prd(prd, relative_path, abs_path.clone());
        by_status.entry(summary.status).or_default().push(summary);
    }

    // Active PRDs section.
    output.push_str("## Active PRDs\n\n");
    if let Some(active) = by_status.get(&PrdStatus::Active) {
        output.push_str(&generate_prd_table(active));
    } else {
        output.push_str("*No active PRDs.*\n");
    }
    output.push('\n');

    // Draft PRDs section.
    output.push_str("## Draft PRDs\n\n");
    if let Some(drafts) = by_status.get(&PrdStatus::Draft) {
        output.push_str(&generate_prd_table(drafts));
    } else {
        output.push_str("*No draft PRDs.*\n");
    }
    output.push('\n');

    // Done PRDs section.
    output.push_str("## Done PRDs\n\n");
    if let Some(done) = by_status.get(&PrdStatus::Done) {
        output.push_str(&generate_prd_table(done));
    } else {
        output.push_str("*No completed PRDs.*\n");
    }
    output.push('\n');

    // Parked PRDs section.
    output.push_str("## Parked PRDs\n\n");
    if let Some(parked) = by_status.get(&PrdStatus::Parked) {
        output.push_str(&generate_prd_table(parked));
    } else {
        output.push_str("*No parked PRDs.*\n");
    }
    output.push('\n');

    // Statistics.
    let total = prds.len();
    let active = by_status.get(&PrdStatus::Active).map_or(0, |v| v.len());
    let draft = by_status.get(&PrdStatus::Draft).map_or(0, |v| v.len());
    let done = by_status.get(&PrdStatus::Done).map_or(0, |v| v.len());
    let parked = by_status.get(&PrdStatus::Parked).map_or(0, |v| v.len());

    output.push_str("## Statistics\n\n");
    output.push_str(&format!("- **Total PRDs**: {}\n", total));
    output.push_str(&format!("- **Active**: {}\n", active));
    output.push_str(&format!("- **Draft**: {}\n", draft));
    output.push_str(&format!("- **Done**: {}\n", done));
    output.push_str(&format!("- **Parked**: {}\n", parked));
    output.push('\n');

    // Footer.
    output.push_str("---\n\n");
    output.push_str(&format!(
        "*Last updated: {}*\n",
        chrono::Local::now().format("%Y-%m-%d")
    ));

    output
}

/// Generates a Markdown table for a list of PRD summaries.
fn generate_prd_table(summaries: &[PrdSummary]) -> String {
    let mut output = String::new();

    // Table header.
    output.push_str("| ID | Title | Status | Progress |\n");
    output.push_str("| -- | ----- | ------ | -------- |\n");

    // Table rows.
    for summary in summaries {
        output.push_str(&format!(
            "| [{}]({}) | {} | {} | {} |\n",
            summary.id,
            summary.relative_path,
            summary.title,
            summary.status,
            summary.progress()
        ));
    }

    output
}

/// Generates the index file and writes it to disk.
///
/// # Arguments
///
/// * `prds_dir` - Path to the directory containing PRD files (e.g., `.mr/prds/`)
/// * `index_path` - Path where the index file should be written (e.g., `.mr/PRDS.md`)
///
/// # Returns
///
/// The number of PRDs included in the index.
pub fn generate_index_file(
    prds_dir: impl AsRef<Path>,
    index_path: impl AsRef<Path>,
) -> Result<usize> {
    let prds = scan_prds(prds_dir)?;
    let count = prds.len();
    let content = generate_index(&prds);

    std::fs::write(index_path.as_ref(), content).with_context(|| {
        format!(
            "Failed to write index file: {}",
            index_path.as_ref().display()
        )
    })?;

    Ok(count)
}

/// Scans PRDs from a repository root and returns PrdSummary objects.
///
/// # Arguments
///
/// * `root` - The repository root directory
///
/// # Returns
///
/// A vector of PrdSummary objects for all successfully parsed PRDs.
pub fn scan_prd_summaries(root: impl AsRef<Path>) -> Result<Vec<PrdSummary>> {
    let prds_dir = root.as_ref().join(".mr").join("prds");
    let prds = scan_prds(&prds_dir)?;

    Ok(prds
        .into_iter()
        .map(|(filename, prd, abs_path)| {
            let relative_path = format!("prds/{}", filename);
            PrdSummary::from_prd(&prd, relative_path, abs_path)
        })
        .collect())
}

/// Generates the index file from a repository root.
///
/// Convenience function that determines paths from the root.
///
/// # Arguments
///
/// * `root` - The repository root directory
///
/// # Returns
///
/// The number of PRDs included in the index.
pub fn generate_index_from_root(root: impl AsRef<Path>) -> Result<usize> {
    let root = root.as_ref();
    let prds_dir = root.join(".mr").join("prds");
    let index_path = root.join(".mr").join("PRDS.md");

    generate_index_file(prds_dir, index_path)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::prd::types::{PrdFrontmatter, Task, TaskStatus};

    fn make_test_prd(id: &str, title: &str, status: PrdStatus, tasks: Vec<Task>) -> Prd {
        let frontmatter = PrdFrontmatter {
            id: id.to_string(),
            title: title.to_string(),
            status,
            tasks: if tasks.is_empty() { None } else { Some(tasks) },
            ..Default::default()
        };

        Prd::new(frontmatter, "# Body\n".to_string())
    }

    fn make_task(id: &str, priority: u32, status: TaskStatus) -> Task {
        Task {
            id: id.to_string(),
            title: format!("Task {}", id),
            priority,
            status,
            notes: None,
        }
    }

    #[test]
    fn test_prd_summary_progress() {
        let prd = make_test_prd(
            "PRD-0001",
            "Test",
            PrdStatus::Active,
            vec![
                make_task("T-001", 1, TaskStatus::Done),
                make_task("T-002", 2, TaskStatus::Done),
                make_task("T-003", 3, TaskStatus::Todo),
            ],
        );

        let summary = PrdSummary::from_prd(
            &prd,
            "prds/test.md".to_string(),
            std::path::PathBuf::from("test.md"),
        );

        assert_eq!(summary.completed_tasks, 2);
        assert_eq!(summary.total_tasks, 3);
        assert_eq!(summary.progress(), "2/3");
    }

    #[test]
    fn test_prd_summary_no_tasks() {
        let prd = make_test_prd("PRD-0001", "Test", PrdStatus::Draft, vec![]);

        let summary = PrdSummary::from_prd(
            &prd,
            "prds/test.md".to_string(),
            std::path::PathBuf::from("test.md"),
        );

        assert_eq!(summary.completed_tasks, 0);
        assert_eq!(summary.total_tasks, 0);
        assert_eq!(summary.progress(), "0/0");
    }

    #[test]
    fn test_generate_prd_table() {
        let summaries = vec![
            PrdSummary {
                id: "PRD-0001".to_string(),
                title: "First PRD".to_string(),
                status: PrdStatus::Active,
                completed_tasks: 2,
                total_tasks: 5,
                relative_path: "prds/PRD-0001.md".to_string(),
                path: std::path::PathBuf::from("prds/PRD-0001.md"),
            },
            PrdSummary {
                id: "PRD-0002".to_string(),
                title: "Second PRD".to_string(),
                status: PrdStatus::Active,
                completed_tasks: 0,
                total_tasks: 3,
                relative_path: "prds/PRD-0002.md".to_string(),
                path: std::path::PathBuf::from("prds/PRD-0002.md"),
            },
        ];

        let table = generate_prd_table(&summaries);

        assert!(table.contains("[PRD-0001](prds/PRD-0001.md)"));
        assert!(table.contains("First PRD"));
        assert!(table.contains("2/5"));
        assert!(table.contains("[PRD-0002](prds/PRD-0002.md)"));
        assert!(table.contains("Second PRD"));
        assert!(table.contains("0/3"));
    }

    #[test]
    fn test_generate_index_empty() {
        let prds: Vec<(String, Prd, std::path::PathBuf)> = vec![];
        let index = generate_index(&prds);

        assert!(index.contains("# Micro Ralph — PRD Index"));
        assert!(index.contains("*No active PRDs.*"));
        assert!(index.contains("*No draft PRDs.*"));
        assert!(index.contains("*No completed PRDs.*"));
        assert!(index.contains("*No parked PRDs.*"));
        assert!(index.contains("**Total PRDs**: 0"));
    }

    #[test]
    fn test_generate_index_with_prds() {
        let prds = vec![
            (
                "PRD-0001.md".to_string(),
                make_test_prd(
                    "PRD-0001",
                    "Active PRD",
                    PrdStatus::Active,
                    vec![
                        make_task("T-001", 1, TaskStatus::Done),
                        make_task("T-002", 2, TaskStatus::Todo),
                    ],
                ),
                std::path::PathBuf::from("prds/PRD-0001.md"),
            ),
            (
                "PRD-0002.md".to_string(),
                make_test_prd("PRD-0002", "Draft PRD", PrdStatus::Draft, vec![]),
                std::path::PathBuf::from("prds/PRD-0002.md"),
            ),
            (
                "PRD-0003.md".to_string(),
                make_test_prd(
                    "PRD-0003",
                    "Done PRD",
                    PrdStatus::Done,
                    vec![make_task("T-001", 1, TaskStatus::Done)],
                ),
                std::path::PathBuf::from("prds/PRD-0003.md"),
            ),
        ];

        let index = generate_index(&prds);

        // Check sections.
        assert!(index.contains("## Active PRDs"));
        assert!(index.contains("[PRD-0001](prds/PRD-0001.md)"));
        assert!(index.contains("Active PRD"));
        assert!(index.contains("1/2"));

        assert!(index.contains("## Draft PRDs"));
        assert!(index.contains("[PRD-0002](prds/PRD-0002.md)"));
        assert!(index.contains("Draft PRD"));

        assert!(index.contains("## Done PRDs"));
        assert!(index.contains("[PRD-0003](prds/PRD-0003.md)"));
        assert!(index.contains("Done PRD"));

        // Check statistics.
        assert!(index.contains("**Total PRDs**: 3"));
        assert!(index.contains("**Active**: 1"));
        assert!(index.contains("**Draft**: 1"));
        assert!(index.contains("**Done**: 1"));
        assert!(index.contains("**Parked**: 0"));
    }

    #[test]
    fn test_scan_prds_from_actual_directory() {
        // Use the actual .mr/prds directory from this repo.
        let prds_dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join(".mr/prds");

        if prds_dir.exists() {
            let prds = scan_prds(&prds_dir).unwrap();

            // Should find at least PRD-0001.
            assert!(!prds.is_empty());

            let prd_0001 = prds.iter().find(|(_, p, _)| p.id() == "PRD-0001");

            assert!(prd_0001.is_some());
        }
    }

    #[test]
    fn test_scan_prds_nonexistent_directory() {
        let prds = scan_prds("/nonexistent/path/to/prds").unwrap();

        assert!(prds.is_empty());
    }
}
